
 CREATE TABLE IF NOT EXISTS Categories (
     Id INT AUTO_INCREMENT PRIMARY KEY,
     Name VARCHAR(255) NOT NULL
 );

 CREATE TABLE IF NOT EXISTS Products (
     Id INT AUTO_INCREMENT PRIMARY KEY,
     Name VARCHAR(255) NOT NULL,
     Price DECIMAL(10, 2) NOT NULL,
     ImageUrl VARCHAR(255)
 );

 CREATE TABLE IF NOT EXISTS ProductCategories (
     ProductId INT,
     CategoryId INT,
     PRIMARY KEY (ProductId, CategoryId),
     FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE,
     FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE CASCADE
 );

 CREATE TABLE IF NOT EXISTS Orders (
     Id INT AUTO_INCREMENT PRIMARY KEY,
     CreateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     ProductId INT NOT NULL,
     Quantity INT NOT NULL,
     Price DECIMAL(10, 2) NOT NULL,
     Amount DECIMAL(10, 2) NOT NULL,
     FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE
 );

 CREATE TABLE IF NOT EXISTS Stocks (
     Id INT AUTO_INCREMENT PRIMARY KEY,
     ProductId INT NOT NULL,
     Stock INT NOT NULL,
     FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE
    );